# code to install packages in the docker file
install.packages("dplyr")
install.packages("readr")
install.packages("magrittr")
install.packages("rvest")
install.packages("stringr")
install.packages("syuzhet")
install.packages("scales")
install.packages("reshape2")
install.packages("gapminder")
install.packages("plumber")
install.packages("DT")
install.packages("shinyjs")
